### ISSUE TITLE
Убрать мусор из репозитория, правильно назвать .gitignore

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework6Ulmart#1]
Каталогов `target`, `*.idea` и т.д. в репо быть не должно.

**Comment by HelgaJava** [comment]
сделано

**Comment by HelgaJava** [comment]
Сделала как вы писали:
Если вы всё-таки залили мусор, то в IDEA нужно:
Alt + F12
В консоли выполнить команды:
git rm --cached -r .idea
git rm --cached -r *.iml
После чего сделать git commit + git push
но target почему-то не убрался

**Comment by HelgaJava** [comment]
Сделала вот как вы сказали:
git rm --cached -r target
все получилось,спасибо
