### ISSUE TITLE
Суффикс и префикс product в данном случае - ни к чему. Если вы напишите просто name и category итак будет понятно, что они относятся к продукту.

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework6Ulmart#3]
https://github.com/HelgaJava/git-homework6Ulmart/blob/1bd804e2d0e72689c3dd72b0b0f5ab11a4f5f49b/src/main/java/ru/itpark/model/Product.java#L14-L15

**Comment by HelgaJava** [comment]
убрала
