### ISSUE TITLE
Обычно к имени класса добавляют тип, например, SortByNameComparator (чтобы сразу было понятно предназначение класса)

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework6Ulmart#5]
https://github.com/HelgaJava/git-homework6Ulmart/blob/1bd804e2d0e72689c3dd72b0b0f5ab11a4f5f49b/src/main/java/ru/itpark/sortProduct/SortByName.java#L7

**Comment by HelgaJava** [comment]
переименовала
также сделала sublist через цикл, так короче код
