### ISSUE TITLE
Нужно ставить break после этого. Иначе ваш продукт будет добавлен два раза, если вы ввели две категории (и у продукта эти же две категории)

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework6Ulmart#6]
https://github.com/HelgaJava/git-homework6Ulmart/blob/a922f171873fbe888dd745e87316e25d6a43dfda/src/main/java/ru/itpark/service/ProductService.java#L56

**Comment by HelgaJava** [comment]
спасибо, исправлено
