### ISSUE TITLE
Избыточное выражение

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework6Ulmart#7]
https://github.com/HelgaJava/git-homework6Ulmart/blob/a922f171873fbe888dd745e87316e25d6a43dfda/src/main/java/ru/itpark/service/ProductService.java#L55

Должно быть просто:
```java
if (product.getCategory().getName().equals(nameCategory)) { ... }
```

**Comment by HelgaJava** [comment]
я исправила, т.е. java сама сама понимает, что если мы не указываем проверку на true, то надо проверять на true? а если нам надо проверить на false, в таком случае как это делать, все-таки "==false" или....?
